// Hardcoded stub responses for /api/summarize.
//
// These exist so the frontend can be built and demoed before the model is
// wired in (Phase 1, build step 2). Step 4 replaces the lookup in
// api/summarize.js with a real model call; this file then becomes the
// reference for what the prompt has to produce, and the offline fallback.
//
// Every sentence below is a restatement or simplification of the matching
// seed document in /data/seed.json. Nothing here diagnoses, prescribes,
// triages, or adds clinical information the source does not contain.

export const FIXTURES = {
  'SYNTH-DISCHARGE-001': {
    documentType: 'hospital discharge summary',
    patientSummary: [
      'You were in the hospital because you had a lung infection called pneumonia. It was in the lower part of your right lung.',
      '',
      'What happened',
      '',
      'Before you came in, you had been coughing up mucus for about four days. You had a fever of 38.9°C, chest pain that got worse when you breathed in, and you got short of breath when you moved around. A chest X-ray showed the infection in your right lung. A blood test showed your white blood cell count was 14.2 — white blood cells are the cells your body uses to fight infection. When you arrived, the oxygen level in your blood was 92%.',
      '',
      'How you were treated',
      '',
      'You were given two antibiotics, ceftriaxone and azithromycin, through an IV — a small tube that goes into a vein. The treatment worked. Your fever was gone for two full days before you went home, and your oxygen level came up to 97% while breathing ordinary room air, with no extra oxygen. You were eating and drinking normally and walking on your own.',
      '',
      'What you need to do now',
      '',
      '- Take amoxicillin-clavulanate, 875/125 mg, twice a day for 5 days. This is the antibiotic you take by mouth now that you are home.',
      '- Keep taking your lisinopril, 10 mg once a day, exactly as you did before.',
      '',
      'What to watch for',
      '',
      'Go back to the hospital or the emergency department if:',
      '',
      '- your breathing gets harder,',
      '- your fever goes above 38.5°C,',
      '- you cough up blood.',
      '',
      'When to follow up',
      '',
      '- See your family doctor in about 1 week.',
      '- You will need another chest X-ray in about 4 to 6 weeks, to check that your lungs have healed.',
    ].join('\n'),
    clinicianHighlights: [
      'Dx: community-acquired pneumonia, RLL — CXR-confirmed consolidation',
      'Presentation: 4d productive cough, T 38.9C, pleuritic CP, exertional SOB; WBC 14.2; SpO2 92% RA',
      'Tx: IV ceftriaxone + azithromycin; afebrile x48h pre-discharge; SpO2 97% RA',
      'Status at d/c: stable, afebrile, tolerating PO, ambulating independently',
      'D/C meds: amoxicillin-clavulanate 875/125 PO BID x5d; continue lisinopril 10mg daily',
      'Follow-up: PCP 7d; repeat CXR 4-6 wks to confirm resolution',
      'Return precautions: worsening dyspnea, fever >38.5C, hemoptysis',
    ],
    glossary: [
      { term: 'pneumonia', plain: 'a lung infection' },
      { term: 'RLL', plain: 'right lower lobe — the lower section of the right lung' },
      { term: 'afebrile', plain: 'no fever' },
      { term: 'productive cough', plain: 'a cough that brings up mucus' },
      { term: 'pleuritic chest pain', plain: 'chest pain that gets worse when you breathe in' },
      { term: 'SOB', plain: 'shortness of breath' },
      { term: 'dyspnea', plain: 'difficulty breathing' },
      { term: 'CXR', plain: 'chest X-ray' },
      { term: 'consolidation', plain: 'an area of lung filled with fluid instead of air, which is how infection shows up on an X-ray' },
      { term: 'WBC', plain: 'white blood cell count — the cells your body uses to fight infection' },
      { term: 'SpO2', plain: 'the oxygen level in your blood' },
      { term: 'RA', plain: 'room air — breathing normally, without extra oxygen' },
      { term: 'IV', plain: 'a small tube placed into a vein to give medicine' },
      { term: 'PO', plain: 'taken by mouth' },
      { term: 'BID', plain: 'twice a day' },
      { term: 'd/c', plain: 'discharge — going home from hospital' },
      { term: 'PCP', plain: 'primary care provider — your family doctor' },
      { term: 'hemoptysis', plain: 'coughing up blood' },
      { term: 'ceftriaxone', plain: 'an antibiotic' },
      { term: 'azithromycin', plain: 'an antibiotic' },
      { term: 'amoxicillin-clavulanate', plain: 'an antibiotic taken by mouth' },
      { term: 'lisinopril', plain: 'a blood pressure medicine' },
    ],
  },

  'SYNTH-DISCHARGE-002': {
    documentType: 'hospital discharge summary',
    patientSummary: [
      'You were in the hospital because your appendix was inflamed and infected. This is called appendicitis. You had surgery to remove it.',
      '',
      'What happened',
      '',
      'You came in with pain in the lower right side of your belly that had lasted about 18 hours. You did not feel like eating, and you had a mild fever. A CT scan — a detailed type of X-ray — showed that your appendix was swollen, with irritation in the fat around it. The scan showed no sign that your appendix had burst. You were taken to the operating room the same day.',
      '',
      'Your surgery',
      '',
      'You had keyhole surgery to remove your appendix. This means the surgeon worked through a few small cuts instead of one large one. The operation went smoothly, with very little blood loss. Your appendix was sent to the lab to be examined. Those results were not ready yet when you went home, so your surgery team will go over them with you at your appointment.',
      '',
      'How you recovered',
      '',
      'You went back to eating regular food and kept it down. Your pain was controlled with medicine taken by mouth. You were walking on your own, passing urine normally, and you had no fever after the operation.',
      '',
      'What you need to do now',
      '',
      '- Acetaminophen, 500 mg, up to every 6 hours as needed for pain.',
      '- Ibuprofen, 400 mg, up to every 8 hours as needed for pain. Stop the ibuprofen if it upsets your stomach.',
      '- Do not lift anything heavier than 10 pounds (about 4.5 kg) for 2 weeks.',
      '- You may shower. Keep the cuts clean and dry.',
      '',
      'What to watch for',
      '',
      'Go back to the hospital or the emergency department if:',
      '',
      '- your temperature goes above 38.5°C,',
      '- the pain in your belly gets worse,',
      '- the cuts become red or start leaking fluid,',
      '- you cannot stop vomiting.',
      '',
      'When to follow up',
      '',
      '- See the surgery clinic in about 10 to 14 days. They will check how your cuts are healing and go over your lab results.',
    ].join('\n'),
    clinicianHighlights: [
      'Dx: acute appendicitis, s/p laparoscopic appendectomy',
      'Presentation: 18h RLQ pain, anorexia, low-grade fever',
      'Imaging: CT abd/pelvis — dilated appendix, periappendiceal fat stranding, no perforation',
      'Procedure: laparoscopic appendectomy, same day, uncomplicated; EBL minimal',
      'Path: specimen sent, results pending at discharge',
      'Post-op: regular diet tolerated, pain controlled on PO analgesia, ambulating, voiding spontaneously, afebrile',
      'D/C meds: acetaminophen 500mg PO q6h PRN; ibuprofen 400mg PO q8h PRN — hold NSAIDs if GI upset',
      'Activity: no lifting >10 lbs x2 wks; may shower, keep incisions clean/dry',
      'Follow-up: surgery clinic 10-14d for wound check + path results',
      'Return precautions: fever >38.5C, worsening abdominal pain, incisional redness/drainage, intractable vomiting',
    ],
    glossary: [
      { term: 'appendicitis', plain: 'an inflamed, infected appendix' },
      { term: 'appendectomy', plain: 'surgery to remove the appendix' },
      { term: 'laparoscopic', plain: 'keyhole surgery, done through a few small cuts' },
      { term: 's/p', plain: 'status post — meaning this has already been done' },
      { term: 'RLQ', plain: 'right lower quadrant — the lower right part of the belly' },
      { term: 'anorexia', plain: 'not feeling like eating' },
      { term: 'CT', plain: 'a detailed type of X-ray scan' },
      { term: 'perforation', plain: 'a burst or torn appendix' },
      { term: 'periappendiceal fat stranding', plain: 'irritation in the fat around the appendix, seen on the scan' },
      { term: 'EBL', plain: 'estimated blood loss during surgery' },
      { term: 'OR', plain: 'operating room' },
      { term: 'path', plain: 'pathology — lab examination of tissue removed during surgery' },
      { term: 'post-op', plain: 'after the operation' },
      { term: 'PO', plain: 'taken by mouth' },
      { term: 'analgesia', plain: 'pain medicine' },
      { term: 'PRN', plain: 'as needed' },
      { term: 'q6h', plain: 'every 6 hours' },
      { term: 'q8h', plain: 'every 8 hours' },
      { term: 'NSAIDs', plain: 'anti-inflammatory painkillers such as ibuprofen' },
      { term: 'acetaminophen', plain: 'a pain and fever medicine, also called paracetamol or Tylenol' },
      { term: 'ibuprofen', plain: 'an anti-inflammatory pain medicine' },
      { term: 'voiding spontaneously', plain: 'passing urine normally on your own' },
      { term: 'intractable vomiting', plain: 'vomiting that will not stop' },
      { term: 'd/c', plain: 'discharge — going home from hospital' },
    ],
  },
};
